env: 'local' #local, dev, prod
type: 'client'
client:
  ipv4: '127.0.0.1'
  ipv6: '127.0.0.1'
  mac: '12.12.12.12'
  port: '10000'

server:
  ipv4: '127.0.0.1'
  ipv6: '127.0.0.1'
  mac: '12.12.12.12'
  port: '10000'
