env: 'local' #local, dev, prod
type: 'client'
interface_name: 'any'
send_interface_name: 'lo'
client:
  ipv4: '192.168.100.100'
  ipv6: '2001:db8:2::10'
  mac:  '02:42:c0:a8:6f:02'
  port: '10000'

server:
  ipv4: '192.168.111.3'
  ipv6: '2001:db8:2::11'
  mac:  '02:42:c0:a8:6f:03'
  port: '10000'
